name: update multicast

on:
  schedule:
    - cron: '30 8 * * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0   
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: 获取组播源
        run: |
          cd $GITHUB_WORKSPACE
          python ./runzb.py         
          
    - name: 推送文件到目标仓库
      run: |
        pip install PyGithub

        GITHUB_TOKEN=${{ secrets.REPO_TOKEN }}

        git clone https://github.com/jk1818/hb.git target_repo
        cd target_repo

        git config --local user.email "actions@163.com"
        git config --local user.name "GitHub Action Bot"

        mkdir -p zubo
        cp ../组播_*.txt zubo/

        if [ -z "$(git status --porcelain)" ]; then
          echo "没有检测到文件变更，跳过提交"
          exit 0
        fi

        git add .
        git commit -m "Update zubo data [skip ci]"
        
        git pull origin main --rebase
        
        git push "https://$GITHUB_TOKEN@github.com/jk1818/hb.git" main