name: PIM Routing Updates

on:
  schedule:
    - cron: '10 2,9 * * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0   
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Multicast Source
        run: |
          cd $GITHUB_WORKSPACE
          python running/runzb.py         
          
      - name: Checkout target repository
        uses: actions/checkout@v3
        with:
          repository: jk1818/hb
          token: ${{ secrets.REPO_TOKEN }}
          path: target-repo

      - name: Copy TXT files to target repository
        run: |
          # Create lv directory if it doesn't exist
          mkdir -p target-repo/zubo
          # Copy all txt files from source to target
          cp -r $GITHUB_WORKSPACE/组播_*.txt target-repo/zubo/
          echo "Files copied to target repository"

      - name: Commit and push to target repository
        run: |
          cd target-repo
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add zubo/
          git commit -m "Update multicast source files"
          git push